[project]
name = "friend_boat"
version = "1.4.7"
description = "A simple music bot for Discord"
authors = ["Michael Genson <71845777+michael-genson@users.noreply.github.com>"]
license = "GNU"
requires-python = ">=3.12,<3.13"
dependencies = [
    "py-cord[voice]>=2.8.1",
    "pydantic-settings>=2.15.0",
    "pynacl>=1.6.2",
    "python-youtube>=0.9.9",
    "slash-cog>=0.0.3",
    "yt-dlp>=2026.7.4",
]

[dependency-groups]
dev = [
    "mypy==2.3.1",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff==0.16.3",
]

[tool.isort]
line_length = 120

[tool.ruff]
extend-exclude = ["deploy/*", "tests/*"]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
ignore = ["BLE001", "LOG015", "S110", "TRY002"]  # TODO: resolve these so we don't have to ignore them

[tool.bumpversion]
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[tool.uv.sources]
py-cord = { git = "https://github.com/Pycord-Development/pycord", rev = "master" }
